import type { Question } from './types';

/**
 * The questionnaire — reflective, first-person questions grouped into five
 * sections. Each option pushes weight onto (dimension, option) pairs defined in
 * dimensions.ts; scoring aggregates them into the user's preference vector and
 * compares it to every school's profile. Skipping a question contributes nothing,
 * so it never penalizes a school.
 */

export const SECTIONS = [
  'Reality & Knowledge',
  'The Good Life',
  'Ethics & Others',
  'Freedom, Meaning & Death',
  'Mind & Temperament',
] as const;

export const QUESTIONS: readonly Question[] = [
  // ───────────────────────── Reality & Knowledge ─────────────────────────
  {
    id: 'q_reality',
    section: 'Reality & Knowledge',
    prompt: 'What is reality ultimately made of?',
    multiSelect: false,
    options: [
      { id: 'matter', label: 'Matter — physical stuff is all there is', contributions: [{ dimension: 'metaphysics', option: 'materialism', weight: 2 }, { dimension: 'attitudeToScience', option: 'science-guide', weight: 0.4 }] },
      { id: 'mind', label: 'Mind or consciousness is fundamental', contributions: [{ dimension: 'metaphysics', option: 'idealism', weight: 2 }] },
      { id: 'both', label: 'Mind and matter are both real and distinct', contributions: [{ dimension: 'metaphysics', option: 'dualism', weight: 2 }] },
      { id: 'one', label: 'All is ultimately one', contributions: [{ dimension: 'metaphysics', option: 'monism', weight: 2 }] },
      { id: 'flux', label: 'Constant change and becoming', contributions: [{ dimension: 'metaphysics', option: 'process', weight: 2 }] },
      { id: 'many', label: 'Many irreducibly different kinds of things', contributions: [{ dimension: 'metaphysics', option: 'pluralism', weight: 2 }] },
      { id: 'unknown', label: 'We can’t really know', contributions: [{ dimension: 'metaphysics', option: 'skeptical', weight: 2 }] },
    ],
  },
  {
    id: 'q_change_permanence',
    section: 'Reality & Knowledge',
    prompt: 'Which feels closer to the truth of things?',
    multiSelect: false,
    options: [
      { id: 'flux', label: 'Everything flows; nothing stays fixed', contributions: [{ dimension: 'metaphysics', option: 'process', weight: 1.5 }] },
      { id: 'unity', label: 'Beneath appearances lies a permanent unity', contributions: [{ dimension: 'metaphysics', option: 'monism', weight: 1.5 }] },
      { id: 'plural', label: 'The world is many separate, real things', contributions: [{ dimension: 'metaphysics', option: 'pluralism', weight: 1.5 }] },
      { id: 'matter', label: 'It’s all just matter in motion', contributions: [{ dimension: 'metaphysics', option: 'materialism', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_mind_matter',
    section: 'Reality & Knowledge',
    prompt: 'Is consciousness simply what the brain does?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — the mind is physical', contributions: [{ dimension: 'metaphysics', option: 'materialism', weight: 1.5 }, { dimension: 'freeWill', option: 'determinism', weight: 0.4 }] },
      { id: 'mind-first', label: 'No — mind comes first', contributions: [{ dimension: 'metaphysics', option: 'idealism', weight: 1.5 }] },
      { id: 'distinct', label: 'Mind and body are distinct', contributions: [{ dimension: 'metaphysics', option: 'dualism', weight: 1.5 }] },
      { id: 'one', label: 'Mind and matter are two faces of one reality', contributions: [{ dimension: 'metaphysics', option: 'monism', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_abstract',
    section: 'Reality & Knowledge',
    prompt: 'Do ideals, forms, or numbers exist in their own right?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — a real realm of forms and ideas', contributions: [{ dimension: 'metaphysics', option: 'idealism', weight: 1 }, { dimension: 'epistemology', option: 'rationalism', weight: 0.6 }] },
      { id: 'no', label: 'No — only concrete physical things are real', contributions: [{ dimension: 'metaphysics', option: 'materialism', weight: 1 }, { dimension: 'epistemology', option: 'empiricism', weight: 0.5 }] },
      { id: 'fictions', label: 'They’re useful fictions, nothing more', contributions: [{ dimension: 'epistemology', option: 'pragmatism', weight: 1 }] },
      { id: 'unknown', label: 'Impossible to settle', contributions: [{ dimension: 'metaphysics', option: 'skeptical', weight: 1 }] },
    ],
  },
  {
    id: 'q_knowledge',
    section: 'Reality & Knowledge',
    prompt: 'How do we best arrive at truth?',
    multiSelect: false,
    options: [
      { id: 'senses', label: 'Through the senses and evidence', contributions: [{ dimension: 'epistemology', option: 'empiricism', weight: 2 }] },
      { id: 'reason', label: 'Through reason and logic', contributions: [{ dimension: 'epistemology', option: 'rationalism', weight: 2 }] },
      { id: 'doubt', label: 'We can’t be certain — suspend judgment', contributions: [{ dimension: 'epistemology', option: 'skepticism', weight: 2 }] },
      { id: 'experience', label: 'Through direct, lived experience', contributions: [{ dimension: 'epistemology', option: 'intuition-experience', weight: 2 }] },
      { id: 'works', label: 'By whatever works in practice', contributions: [{ dimension: 'epistemology', option: 'pragmatism', weight: 2 }] },
    ],
  },
  {
    id: 'q_certainty',
    section: 'Reality & Knowledge',
    prompt: 'How much can we really know for certain?',
    multiSelect: false,
    options: [
      { id: 'much', label: 'Quite a lot, with the right method', contributions: [{ dimension: 'epistemology', option: 'rationalism', weight: 0.8 }, { dimension: 'attitudeToScience', option: 'science-guide', weight: 0.6 }] },
      { id: 'little', label: 'Little for certain — better to keep doubting', contributions: [{ dimension: 'epistemology', option: 'skepticism', weight: 1.5 }, { dimension: 'metaphilosophy', option: 'skeptical-inquiry', weight: 0.6 }] },
      { id: 'enough', label: 'Enough to act well, which is what matters', contributions: [{ dimension: 'epistemology', option: 'pragmatism', weight: 1.5 }] },
      { id: 'lived', label: 'Truth is something we live more than prove', contributions: [{ dimension: 'epistemology', option: 'intuition-experience', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_belief_warrant',
    section: 'Reality & Knowledge',
    prompt: 'A belief earns your acceptance when…',
    multiSelect: false,
    options: [
      { id: 'evidence', label: 'There is solid empirical evidence', contributions: [{ dimension: 'epistemology', option: 'empiricism', weight: 1.5 }, { dimension: 'attitudeToScience', option: 'science-guide', weight: 0.5 }] },
      { id: 'proof', label: 'It can be logically demonstrated', contributions: [{ dimension: 'epistemology', option: 'rationalism', weight: 1.5 }] },
      { id: 'useful', label: 'It proves useful in living', contributions: [{ dimension: 'epistemology', option: 'pragmatism', weight: 1.5 }] },
      { id: 'never', label: 'Never fully — hold all beliefs lightly', contributions: [{ dimension: 'epistemology', option: 'skepticism', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_science',
    section: 'Reality & Knowledge',
    prompt: 'How much should we defer to science?',
    multiSelect: false,
    options: [
      { id: 'guide', label: 'It’s our best guide to what’s true', contributions: [{ dimension: 'attitudeToScience', option: 'science-guide', weight: 2 }, { dimension: 'metaphysics', option: 'materialism', weight: 0.4 }] },
      { id: 'limited', label: 'Powerful, but it can’t answer everything', contributions: [{ dimension: 'attitudeToScience', option: 'science-limited', weight: 2 }] },
      { id: 'critical', label: 'Its authority should be questioned', contributions: [{ dimension: 'attitudeToScience', option: 'science-critical', weight: 2 }] },
      { id: 'neutral', label: 'Not really my concern', contributions: [{ dimension: 'attitudeToScience', option: 'neutral', weight: 2 }] },
    ],
  },

  // ─────────────────────────── The Good Life ───────────────────────────
  {
    id: 'q_highest_good',
    section: 'The Good Life',
    prompt: 'What is a genuinely good life ultimately about?',
    multiSelect: false,
    options: [
      { id: 'pleasure', label: 'Pleasure and enjoyment', contributions: [{ dimension: 'theGoodLife', option: 'pleasure', weight: 2 }] },
      { id: 'peace', label: 'Peace of mind and calm', contributions: [{ dimension: 'theGoodLife', option: 'tranquility', weight: 2 }] },
      { id: 'virtue', label: 'Virtue and flourishing', contributions: [{ dimension: 'theGoodLife', option: 'virtue-excellence', weight: 2 }] },
      { id: 'duty', label: 'Duty, honor, and integrity', contributions: [{ dimension: 'theGoodLife', option: 'duty-honor', weight: 2 }] },
      { id: 'self', label: 'Becoming your fullest self', contributions: [{ dimension: 'theGoodLife', option: 'self-actualization', weight: 2 }] },
      { id: 'liberation', label: 'Freedom from suffering', contributions: [{ dimension: 'theGoodLife', option: 'liberation', weight: 2 }] },
      { id: 'meaning', label: 'Meaning you forge yourself', contributions: [{ dimension: 'theGoodLife', option: 'meaning-creation', weight: 2 }] },
      { id: 'truth', label: 'Understanding and truth', contributions: [{ dimension: 'theGoodLife', option: 'knowledge', weight: 2 }] },
    ],
  },
  {
    id: 'q_pleasure_view',
    section: 'The Good Life',
    prompt: 'How should we treat bodily pleasure and comfort?',
    multiSelect: false,
    options: [
      { id: 'embrace', label: 'Embrace and enjoy them', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 1.5 }, { dimension: 'desireStance', option: 'embrace', weight: 1 }] },
      { id: 'moderate', label: 'Enjoy them in moderation', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 1.5 }, { dimension: 'desireStance', option: 'moderate', weight: 1 }] },
      { id: 'discipline', label: 'Keep them firmly disciplined', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 1.5 }, { dimension: 'desireStance', option: 'master', weight: 1 }] },
      { id: 'transcend', label: 'Rise beyond such desires entirely', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 1 }, { dimension: 'desireStance', option: 'transcend', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_desire',
    section: 'The Good Life',
    prompt: 'What is the ideal relationship with desire and emotion?',
    multiSelect: false,
    options: [
      { id: 'transcend', label: 'Extinguish craving and transcend it', contributions: [{ dimension: 'desireStance', option: 'transcend', weight: 2 }] },
      { id: 'master', label: 'Master and discipline the passions', contributions: [{ dimension: 'desireStance', option: 'master', weight: 2 }] },
      { id: 'moderate', label: 'Enjoy in balanced moderation', contributions: [{ dimension: 'desireStance', option: 'moderate', weight: 2 }] },
      { id: 'embrace', label: 'Fully embrace desire and feeling', contributions: [{ dimension: 'desireStance', option: 'embrace', weight: 2 }] },
    ],
  },
  {
    id: 'q_simplicity',
    section: 'The Good Life',
    prompt: 'The good life calls for…',
    multiSelect: false,
    options: [
      { id: 'simple', label: 'Few wants…simplicity and self-sufficiency', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 1.5 }] },
      { id: 'enough', label: 'Balance — enough, and no more', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 1.5 }] },
      { id: 'abundance', label: 'Rich experience and abundance', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_wealth',
    section: 'The Good Life',
    prompt: 'Worldly success and possessions are…',
    multiSelect: false,
    options: [
      { id: 'good', label: 'Good things — enjoy them', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 1.5 }] },
      { id: 'fine', label: 'Fine in moderation', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 1.5 }] },
      { id: 'distraction', label: 'Distractions best minimized', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_adversity',
    section: 'The Good Life',
    prompt: 'When life turns hard, the wisest response is to…',
    multiSelect: false,
    options: [
      { id: 'accept', label: 'Stay serene; accept what you can’t control', contributions: [{ dimension: 'theGoodLife', option: 'tranquility', weight: 1 }, { dimension: 'desireStance', option: 'master', weight: 0.8 }, { dimension: 'viewOfDeath', option: 'acceptance', weight: 0.4 }] },
      { id: 'meaning', label: 'Find or create meaning in it', contributions: [{ dimension: 'theGoodLife', option: 'meaning-creation', weight: 1 }, { dimension: 'meaningSource', option: 'self-created', weight: 0.6 }] },
      { id: 'reduce', label: 'Work to reduce the suffering', contributions: [{ dimension: 'ethicsBasis', option: 'care-compassion', weight: 0.8 }, { dimension: 'theGoodLife', option: 'liberation', weight: 0.6 }] },
      { id: 'enjoy', label: 'Savor whatever good still remains', contributions: [{ dimension: 'theGoodLife', option: 'pleasure', weight: 0.8 }, { dimension: 'desireStance', option: 'moderate', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_time_use',
    section: 'The Good Life',
    prompt: 'A free afternoon is best spent…',
    multiSelect: false,
    options: [
      { id: 'reflect', label: 'In quiet reflection or meditation', contributions: [{ dimension: 'theGoodLife', option: 'tranquility', weight: 1 }, { dimension: 'metaphilosophy', option: 'therapeutic', weight: 0.5 }] },
      { id: 'learn', label: 'Learning or understanding something', contributions: [{ dimension: 'theGoodLife', option: 'knowledge', weight: 1 }] },
      { id: 'loved', label: 'With people you love', contributions: [{ dimension: 'meaningSource', option: 'relationships', weight: 1 }, { dimension: 'selfSociety', option: 'relational', weight: 0.5 }] },
      { id: 'pleasure', label: 'Enjoying a real pleasure', contributions: [{ dimension: 'theGoodLife', option: 'pleasure', weight: 1 }, { dimension: 'worldStance', option: 'affirming', weight: 0.4 }] },
      { id: 'cause', label: 'Working on a cause that matters', contributions: [{ dimension: 'meaningSource', option: 'progress', weight: 1 }, { dimension: 'metaphilosophy', option: 'political-praxis', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_suffering',
    section: 'The Good Life',
    prompt: 'Suffering, at bottom, is…',
    multiSelect: false,
    options: [
      { id: 'accept', label: 'To be met with equanimity', contributions: [{ dimension: 'desireStance', option: 'master', weight: 1 }, { dimension: 'viewOfDeath', option: 'acceptance', weight: 0.5 }] },
      { id: 'reduce', label: 'To be reduced wherever we can', contributions: [{ dimension: 'ethicsBasis', option: 'care-compassion', weight: 1 }, { dimension: 'moralScope', option: 'all-sentient', weight: 0.6 }] },
      { id: 'teacher', label: 'A teacher that can give life meaning', contributions: [{ dimension: 'theGoodLife', option: 'meaning-creation', weight: 1 }, { dimension: 'viewOfDeath', option: 'memento-mori', weight: 0.5 }] },
      { id: 'illusion', label: 'Rooted in craving — to be seen through', contributions: [{ dimension: 'desireStance', option: 'transcend', weight: 1 }, { dimension: 'theGoodLife', option: 'liberation', weight: 0.8 }] },
    ],
  },
  {
    id: 'q_authenticity',
    section: 'The Good Life',
    prompt: 'It matters most to…',
    multiSelect: false,
    options: [
      { id: 'self', label: 'Be true to your own self', contributions: [{ dimension: 'theGoodLife', option: 'self-actualization', weight: 1 }, { dimension: 'selfSociety', option: 'individualist', weight: 0.6 }] },
      { id: 'role', label: 'Fulfill your role in society well', contributions: [{ dimension: 'selfSociety', option: 'communitarian', weight: 1 }, { dimension: 'theGoodLife', option: 'duty-honor', weight: 0.6 }] },
      { id: 'question', label: 'Question everything you were handed', contributions: [{ dimension: 'metaphilosophy', option: 'skeptical-inquiry', weight: 1 }] },
      { id: 'connect', label: 'Connect deeply with others', contributions: [{ dimension: 'selfSociety', option: 'relational', weight: 1 }, { dimension: 'meaningSource', option: 'relationships', weight: 0.5 }] },
    ],
  },

  // ─────────────────────────── Ethics & Others ───────────────────────────
  {
    id: 'q_right_wrong',
    section: 'Ethics & Others',
    prompt: 'What ultimately makes an action right?',
    multiSelect: false,
    options: [
      { id: 'virtue', label: 'It flows from good character', contributions: [{ dimension: 'ethicsBasis', option: 'virtue', weight: 2 }] },
      { id: 'outcomes', label: 'It brings about the best outcomes', contributions: [{ dimension: 'ethicsBasis', option: 'consequences', weight: 2 }] },
      { id: 'duty', label: 'It follows a universal duty or principle', contributions: [{ dimension: 'ethicsBasis', option: 'duty', weight: 2 }] },
      { id: 'self', label: 'It serves rational self-interest', contributions: [{ dimension: 'ethicsBasis', option: 'egoism', weight: 2 }] },
      { id: 'care', label: 'It expresses care and compassion', contributions: [{ dimension: 'ethicsBasis', option: 'care-compassion', weight: 2 }] },
      { id: 'contract', label: 'It honors a fair agreement', contributions: [{ dimension: 'ethicsBasis', option: 'social-contract', weight: 2 }] },
      { id: 'relative', label: 'Nothing universal — it’s relative', contributions: [{ dimension: 'ethicsBasis', option: 'relativism', weight: 2 }] },
      { id: 'natural', label: 'It fits a natural moral order', contributions: [{ dimension: 'ethicsBasis', option: 'natural-law', weight: 2 }] },
    ],
  },
  {
    id: 'q_moral_dilemma',
    section: 'Ethics & Others',
    prompt: 'Facing a hard choice, the question you ask is…',
    multiSelect: false,
    options: [
      { id: 'character', label: '“What would a person of good character do?”', contributions: [{ dimension: 'ethicsBasis', option: 'virtue', weight: 1.5 }] },
      { id: 'best', label: '“What produces the most good overall?”', contributions: [{ dimension: 'ethicsBasis', option: 'consequences', weight: 1.5 }] },
      { id: 'duty', label: '“What’s my duty, whatever the result?”', contributions: [{ dimension: 'ethicsBasis', option: 'duty', weight: 1.5 }] },
      { id: 'fair', label: '“What’s fair — what would we all agree to?”', contributions: [{ dimension: 'ethicsBasis', option: 'social-contract', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_justice',
    section: 'Ethics & Others',
    prompt: 'A just society, above all,…',
    multiSelect: false,
    options: [
      { id: 'welfare', label: 'Maximizes overall wellbeing', contributions: [{ dimension: 'ethicsBasis', option: 'consequences', weight: 1 }, { dimension: 'moralScope', option: 'all-humans', weight: 0.5 }] },
      { id: 'liberty', label: 'Protects individual rights and liberty', contributions: [{ dimension: 'selfSociety', option: 'individualist', weight: 1 }, { dimension: 'ethicsBasis', option: 'duty', weight: 0.5 }] },
      { id: 'fairness', label: 'Ensures fairness for the worst-off', contributions: [{ dimension: 'ethicsBasis', option: 'social-contract', weight: 1 }, { dimension: 'changeOrientation', option: 'reform-progress', weight: 0.5 }] },
      { id: 'order', label: 'Preserves tradition, order, and cohesion', contributions: [{ dimension: 'selfSociety', option: 'communitarian', weight: 1 }, { dimension: 'changeOrientation', option: 'conserve', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_rules_relative',
    section: 'Ethics & Others',
    prompt: 'Moral truths are…',
    multiSelect: false,
    options: [
      { id: 'objective', label: 'Objective and universal', contributions: [{ dimension: 'ethicsBasis', option: 'natural-law', weight: 1 }, { dimension: 'ethicsBasis', option: 'duty', weight: 0.5 }] },
      { id: 'outcomes', label: 'About real effects on wellbeing', contributions: [{ dimension: 'ethicsBasis', option: 'consequences', weight: 1 }] },
      { id: 'cultural', label: 'Relative to culture and era', contributions: [{ dimension: 'ethicsBasis', option: 'relativism', weight: 1.5 }] },
      { id: 'preference', label: 'Really just human preferences', contributions: [{ dimension: 'ethicsBasis', option: 'relativism', weight: 1 }, { dimension: 'ethicsBasis', option: 'egoism', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_moral_circle',
    section: 'Ethics & Others',
    prompt: 'Whose wellbeing should we weigh in our choices?',
    multiSelect: false,
    options: [
      { id: 'self', label: 'Chiefly my own', contributions: [{ dimension: 'moralScope', option: 'self', weight: 2 }] },
      { id: 'community', label: 'My family and community', contributions: [{ dimension: 'moralScope', option: 'community', weight: 2 }] },
      { id: 'humans', label: 'All human beings', contributions: [{ dimension: 'moralScope', option: 'all-humans', weight: 2 }] },
      { id: 'sentient', label: 'All beings that can suffer', contributions: [{ dimension: 'moralScope', option: 'all-sentient', weight: 2 }] },
      { id: 'nature', label: 'All of nature', contributions: [{ dimension: 'moralScope', option: 'all-nature', weight: 2 }] },
    ],
  },
  {
    id: 'q_altruism',
    section: 'Ethics & Others',
    prompt: 'How much do we owe distant strangers?',
    multiSelect: false,
    options: [
      { id: 'most-good', label: 'Do the most good you can for all', contributions: [{ dimension: 'ethicsBasis', option: 'consequences', weight: 1 }, { dimension: 'moralScope', option: 'all-sentient', weight: 0.8 }] },
      { id: 'dignity', label: 'Treat each as an end in themselves', contributions: [{ dimension: 'ethicsBasis', option: 'duty', weight: 1 }, { dimension: 'moralScope', option: 'all-humans', weight: 0.6 }] },
      { id: 'near', label: 'Care first for those close to you', contributions: [{ dimension: 'ethicsBasis', option: 'care-compassion', weight: 1 }, { dimension: 'moralScope', option: 'community', weight: 0.7 }] },
      { id: 'self', label: 'Look after yourself first', contributions: [{ dimension: 'ethicsBasis', option: 'egoism', weight: 1 }, { dimension: 'moralScope', option: 'self', weight: 0.7 }] },
    ],
  },
  {
    id: 'q_self_society',
    section: 'Ethics & Others',
    prompt: 'Which matters more?',
    multiSelect: false,
    options: [
      { id: 'individual', label: 'The freedom of the individual', contributions: [{ dimension: 'selfSociety', option: 'individualist', weight: 2 }] },
      { id: 'community', label: 'The good of the community', contributions: [{ dimension: 'selfSociety', option: 'communitarian', weight: 2 }] },
      { id: 'humanity', label: 'All humanity as one', contributions: [{ dimension: 'selfSociety', option: 'cosmopolitan', weight: 2 }] },
      { id: 'relational', label: 'We only exist through relationships', contributions: [{ dimension: 'selfSociety', option: 'relational', weight: 2 }] },
    ],
  },
  {
    id: 'q_human_nature',
    section: 'Ethics & Others',
    prompt: 'People are fundamentally…',
    multiSelect: false,
    options: [
      { id: 'good', label: 'Basically good and improvable', contributions: [{ dimension: 'humanNature', option: 'perfectible', weight: 2 }] },
      { id: 'flawed', label: 'Flawed and largely fixed', contributions: [{ dimension: 'humanNature', option: 'fixed-flawed', weight: 2 }] },
      { id: 'shaped', label: 'Shaped by environment and habit', contributions: [{ dimension: 'humanNature', option: 'blank-slate', weight: 2 }] },
      { id: 'social', label: 'Social creatures through and through', contributions: [{ dimension: 'humanNature', option: 'social', weight: 2 }] },
      { id: 'selfish', label: 'Basically self-interested', contributions: [{ dimension: 'humanNature', option: 'self-interested', weight: 2 }] },
    ],
  },

  // ────────────────────── Freedom, Meaning & Death ──────────────────────
  {
    id: 'q_free_will',
    section: 'Freedom, Meaning & Death',
    prompt: 'Are our choices truly free?',
    multiSelect: false,
    options: [
      { id: 'free', label: 'Yes — we have real free will', contributions: [{ dimension: 'freeWill', option: 'libertarian-free', weight: 2 }] },
      { id: 'determined', label: 'No — everything is determined', contributions: [{ dimension: 'freeWill', option: 'determinism', weight: 2 }] },
      { id: 'both', label: 'Free and determined are compatible', contributions: [{ dimension: 'freeWill', option: 'compatibilism', weight: 2 }] },
      { id: 'nomatter', label: 'Not something I dwell on', contributions: [{ dimension: 'freeWill', option: 'not-central', weight: 2 }] },
    ],
  },
  {
    id: 'q_fate',
    section: 'Freedom, Meaning & Death',
    prompt: 'The wise stance toward fate is to…',
    multiSelect: false,
    options: [
      { id: 'amor-fati', label: 'Accept, even love, whatever happens', contributions: [{ dimension: 'viewOfDeath', option: 'acceptance', weight: 0.8 }, { dimension: 'freeWill', option: 'determinism', weight: 0.8 }, { dimension: 'desireStance', option: 'master', weight: 0.4 }] },
      { id: 'defy', label: 'Assert your freedom against it', contributions: [{ dimension: 'freeWill', option: 'libertarian-free', weight: 1 }, { dimension: 'meaningSource', option: 'self-created', weight: 0.5 }] },
      { id: 'change', label: 'Change what you can, accept the rest', contributions: [{ dimension: 'freeWill', option: 'compatibilism', weight: 1 }, { dimension: 'meaningSource', option: 'progress', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_meaning',
    section: 'Freedom, Meaning & Death',
    prompt: 'Where does life’s meaning come from?',
    multiSelect: false,
    options: [
      { id: 'cosmic', label: 'A cosmic order to align with', contributions: [{ dimension: 'meaningSource', option: 'cosmic-order', weight: 2 }] },
      { id: 'self', label: 'Meaning we create for ourselves', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 2 }] },
      { id: 'love', label: 'Love, relationships, and community', contributions: [{ dimension: 'meaningSource', option: 'relationships', weight: 2 }] },
      { id: 'progress', label: 'Improving the world and the future', contributions: [{ dimension: 'meaningSource', option: 'progress', weight: 2 }] },
      { id: 'none', label: 'There’s none inherent — and that’s okay', contributions: [{ dimension: 'meaningSource', option: 'none-and-ok', weight: 2 }] },
    ],
  },
  {
    id: 'q_universe',
    section: 'Freedom, Meaning & Death',
    prompt: 'The universe, in relation to us, is…',
    multiSelect: false,
    options: [
      { id: 'ordered', label: 'An order we can attune ourselves to', contributions: [{ dimension: 'meaningSource', option: 'cosmic-order', weight: 1.5 }] },
      { id: 'indifferent', label: 'Indifferent — meaning is ours to make', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 1 }, { dimension: 'metaphysics', option: 'materialism', weight: 0.5 }] },
      { id: 'improving', label: 'Something we can push toward better', contributions: [{ dimension: 'meaningSource', option: 'progress', weight: 1.5 }] },
      { id: 'oneness', label: 'A whole we’re inseparably part of', contributions: [{ dimension: 'metaphysics', option: 'monism', weight: 1 }, { dimension: 'moralScope', option: 'all-nature', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_purpose',
    section: 'Freedom, Meaning & Death',
    prompt: 'Which most give your life meaning? (Choose any.)',
    multiSelect: true,
    options: [
      { id: 'projects', label: 'Projects and things I create', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 1 }, { dimension: 'theGoodLife', option: 'self-actualization', weight: 0.5 }] },
      { id: 'loved', label: 'The people I love', contributions: [{ dimension: 'meaningSource', option: 'relationships', weight: 1 }, { dimension: 'selfSociety', option: 'relational', weight: 0.4 }] },
      { id: 'better', label: 'Leaving the world better', contributions: [{ dimension: 'meaningSource', option: 'progress', weight: 1 }, { dimension: 'moralScope', option: 'all-humans', weight: 0.4 }] },
      { id: 'truth', label: 'Understanding how things really are', contributions: [{ dimension: 'theGoodLife', option: 'knowledge', weight: 1 }] },
      { id: 'peace', label: 'Reaching inner peace', contributions: [{ dimension: 'theGoodLife', option: 'tranquility', weight: 1 }] },
      { id: 'virtue', label: 'Living with virtue and integrity', contributions: [{ dimension: 'theGoodLife', option: 'virtue-excellence', weight: 1 }] },
    ],
  },
  {
    id: 'q_death',
    section: 'Freedom, Meaning & Death',
    prompt: 'How should we regard death?',
    multiSelect: false,
    options: [
      { id: 'accept', label: 'Accept it calmly as natural', contributions: [{ dimension: 'viewOfDeath', option: 'acceptance', weight: 2 }] },
      { id: 'detach', label: 'Detach from it and rise above', contributions: [{ dimension: 'viewOfDeath', option: 'transcend-detach', weight: 2 }] },
      { id: 'memento', label: 'Let it sharpen how we live now', contributions: [{ dimension: 'viewOfDeath', option: 'memento-mori', weight: 2 }] },
      { id: 'nothing', label: 'It’s nothing to us — no fear needed', contributions: [{ dimension: 'viewOfDeath', option: 'irrelevant', weight: 2 }] },
      { id: 'continue', label: 'Something continues on', contributions: [{ dimension: 'viewOfDeath', option: 'continuation', weight: 2 }] },
    ],
  },
  {
    id: 'q_no_meaning',
    section: 'Freedom, Meaning & Death',
    prompt: 'If life has no built-in purpose, that is…',
    multiSelect: false,
    options: [
      { id: 'freeing', label: 'Freeing — I get to make my own', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 1.5 }, { dimension: 'meaningSource', option: 'none-and-ok', weight: 0.5 }] },
      { id: 'fine', label: 'Simply true, and I’m at peace with it', contributions: [{ dimension: 'meaningSource', option: 'none-and-ok', weight: 1.5 }] },
      { id: 'false', label: 'False — there is a deeper order', contributions: [{ dimension: 'meaningSource', option: 'cosmic-order', weight: 1.5 }] },
      { id: 'progress', label: 'We build purpose by bettering things', contributions: [{ dimension: 'meaningSource', option: 'progress', weight: 1.5 }] },
    ],
  },

  // ─────────────────────────── Mind & Temperament ───────────────────────────
  {
    id: 'q_head_heart',
    section: 'Mind & Temperament',
    prompt: 'In living well, which should lead?',
    multiSelect: false,
    options: [
      { id: 'reason', label: 'Reason', contributions: [{ dimension: 'emotionReason', option: 'reason-primary', weight: 2 }] },
      { id: 'emotion', label: 'Emotion carries real wisdom', contributions: [{ dimension: 'emotionReason', option: 'emotion-valued', weight: 2 }] },
      { id: 'balance', label: 'A balance of both', contributions: [{ dimension: 'emotionReason', option: 'balance', weight: 2 }] },
      { id: 'beyond', label: 'Quiet both and see clearly', contributions: [{ dimension: 'emotionReason', option: 'beyond-both', weight: 2 }] },
    ],
  },
  {
    id: 'q_emotions_role',
    section: 'Mind & Temperament',
    prompt: 'Strong emotions are best…',
    multiSelect: false,
    options: [
      { id: 'governed', label: 'Governed firmly by reason', contributions: [{ dimension: 'emotionReason', option: 'reason-primary', weight: 1 }, { dimension: 'desireStance', option: 'master', weight: 0.6 }] },
      { id: 'heeded', label: 'Heeded as a source of insight', contributions: [{ dimension: 'emotionReason', option: 'emotion-valued', weight: 1.5 }] },
      { id: 'expressed', label: 'Felt fully and expressed', contributions: [{ dimension: 'desireStance', option: 'embrace', weight: 1 }, { dimension: 'emotionReason', option: 'emotion-valued', weight: 0.6 }] },
      { id: 'quieted', label: 'Quieted until they fade', contributions: [{ dimension: 'desireStance', option: 'transcend', weight: 1 }, { dimension: 'emotionReason', option: 'beyond-both', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_change',
    section: 'Mind & Temperament',
    prompt: 'When it comes to change, society should…',
    multiSelect: false,
    options: [
      { id: 'restore', label: 'Recover the wisdom of the past', contributions: [{ dimension: 'changeOrientation', option: 'restore-classical', weight: 2 }] },
      { id: 'conserve', label: 'Preserve what already works', contributions: [{ dimension: 'changeOrientation', option: 'conserve', weight: 2 }] },
      { id: 'reform', label: 'Steadily reform and improve', contributions: [{ dimension: 'changeOrientation', option: 'reform-progress', weight: 2 }] },
      { id: 'radical', label: 'Be radically transformed', contributions: [{ dimension: 'changeOrientation', option: 'radical-transform', weight: 2 }] },
    ],
  },
  {
    id: 'q_history',
    section: 'Mind & Temperament',
    prompt: 'Human history is broadly…',
    multiSelect: false,
    options: [
      { id: 'decline', label: 'A decline from a wiser past', contributions: [{ dimension: 'changeOrientation', option: 'restore-classical', weight: 1.5 }] },
      { id: 'progress', label: 'Improving over time', contributions: [{ dimension: 'changeOrientation', option: 'reform-progress', weight: 1 }, { dimension: 'meaningSource', option: 'progress', weight: 0.6 }] },
      { id: 'nowhere', label: 'Going nowhere in particular', contributions: [{ dimension: 'meaningSource', option: 'none-and-ok', weight: 1 }] },
      { id: 'remake', label: 'Ours to radically remake', contributions: [{ dimension: 'changeOrientation', option: 'radical-transform', weight: 1.5 }, { dimension: 'metaphilosophy', option: 'political-praxis', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_philosophy_for',
    section: 'Mind & Temperament',
    prompt: 'Philosophy is, above all,…',
    multiSelect: false,
    options: [
      { id: 'life', label: 'A way of life to practice daily', contributions: [{ dimension: 'metaphilosophy', option: 'way-of-life', weight: 2 }] },
      { id: 'system', label: 'A system that explains everything', contributions: [{ dimension: 'metaphilosophy', option: 'system-theory', weight: 2 }] },
      { id: 'inquiry', label: 'Endless questioning and inquiry', contributions: [{ dimension: 'metaphilosophy', option: 'skeptical-inquiry', weight: 2 }] },
      { id: 'praxis', label: 'A tool to change society', contributions: [{ dimension: 'metaphilosophy', option: 'political-praxis', weight: 2 }] },
      { id: 'therapy', label: 'A cure for anxiety and confusion', contributions: [{ dimension: 'metaphilosophy', option: 'therapeutic', weight: 2 }] },
    ],
  },
  {
    id: 'q_improve',
    section: 'Mind & Temperament',
    prompt: 'Can people fundamentally improve themselves?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — we’re perfectible', contributions: [{ dimension: 'humanNature', option: 'perfectible', weight: 1.5 }] },
      { id: 'no', label: 'Not really — our nature is fixed', contributions: [{ dimension: 'humanNature', option: 'fixed-flawed', weight: 1.5 }] },
      { id: 'env', label: 'It depends on their environment', contributions: [{ dimension: 'humanNature', option: 'blank-slate', weight: 1.5 }] },
      { id: 'together', label: 'Only together, through others', contributions: [{ dimension: 'humanNature', option: 'social', weight: 1.5 }, { dimension: 'selfSociety', option: 'relational', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_freedom_order',
    section: 'Mind & Temperament',
    prompt: 'Which do you prize more?',
    multiSelect: false,
    options: [
      { id: 'freedom', label: 'Individual freedom', contributions: [{ dimension: 'selfSociety', option: 'individualist', weight: 1.5 }] },
      { id: 'harmony', label: 'Social harmony and order', contributions: [{ dimension: 'selfSociety', option: 'communitarian', weight: 1 }, { dimension: 'changeOrientation', option: 'conserve', weight: 0.5 }] },
      { id: 'equality', label: 'Equality and solidarity', contributions: [{ dimension: 'selfSociety', option: 'cosmopolitan', weight: 1 }, { dimension: 'moralScope', option: 'all-humans', weight: 0.5 }] },
      { id: 'change', label: 'Overturning unjust structures', contributions: [{ dimension: 'changeOrientation', option: 'radical-transform', weight: 1 }, { dimension: 'metaphilosophy', option: 'political-praxis', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_temperament',
    section: 'Mind & Temperament',
    prompt: 'Which describe your outlook? (Choose any.)',
    multiSelect: true,
    options: [
      { id: 'skeptical', label: 'Skeptical and questioning', contributions: [{ dimension: 'metaphilosophy', option: 'skeptical-inquiry', weight: 1 }, { dimension: 'epistemology', option: 'skepticism', weight: 0.5 }] },
      { id: 'disciplined', label: 'Disciplined and self-controlled', contributions: [{ dimension: 'desireStance', option: 'master', weight: 1 }, { dimension: 'emotionReason', option: 'reason-primary', weight: 0.5 }] },
      { id: 'warm', label: 'Warm and relational', contributions: [{ dimension: 'selfSociety', option: 'relational', weight: 1 }, { dimension: 'emotionReason', option: 'emotion-valued', weight: 0.5 }] },
      { id: 'free', label: 'Rebellious and free-spirited', contributions: [{ dimension: 'selfSociety', option: 'individualist', weight: 1 }, { dimension: 'freeWill', option: 'libertarian-free', weight: 0.5 }] },
      { id: 'practical', label: 'Practical and results-focused', contributions: [{ dimension: 'epistemology', option: 'pragmatism', weight: 1 }, { dimension: 'ethicsBasis', option: 'consequences', weight: 0.5 }] },
      { id: 'inward', label: 'Contemplative and inward', contributions: [{ dimension: 'epistemology', option: 'intuition-experience', weight: 0.8 }, { dimension: 'theGoodLife', option: 'tranquility', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_nature_rel',
    section: 'Mind & Temperament',
    prompt: 'Our relationship to nature is best seen as…',
    multiSelect: false,
    options: [
      { id: 'oneness', label: 'Being part of one living whole', contributions: [{ dimension: 'moralScope', option: 'all-nature', weight: 1.5 }, { dimension: 'metaphysics', option: 'monism', weight: 0.5 }] },
      { id: 'stewards', label: 'Stewards who should minimize harm', contributions: [{ dimension: 'moralScope', option: 'all-sentient', weight: 1 }, { dimension: 'ethicsBasis', option: 'care-compassion', weight: 0.5 }] },
      { id: 'resource', label: 'A resource for human flourishing', contributions: [{ dimension: 'moralScope', option: 'all-humans', weight: 0.8 }, { dimension: 'attitudeToScience', option: 'science-guide', weight: 0.4 }] },
      { id: 'simple', label: 'Something to live simply within', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 0.8 }, { dimension: 'moralScope', option: 'all-nature', weight: 0.6 }] },
    ],
  },
];
