import type { Question } from './types';

/**
 * The questionnaire. ~50 questions grouped into thematic sections. Each option
 * pushes weight onto (dimension, option) pairs defined in dimensions.ts; the
 * scoring engine aggregates those into the user's preference vector and compares
 * it to every religion's profile.
 *
 * Questions with `multiSelect: true` let the user endorse several answers that
 * resonate. Any question can be left unanswered ("no preference") — it then
 * contributes nothing, so skipping never penalizes a tradition.
 */

export const SECTIONS = [
  'The Divine',
  'Truth & Authority',
  'Purpose & Afterlife',
  'Practice & Community',
  'Ethics, Society & Style',
  'Meaning, Ethics & Temperament',
] as const;

export const QUESTIONS: readonly Question[] = [
  // ────────────────────────────── The Divine ──────────────────────────────
  {
    id: 'q_god_count',
    section: 'The Divine',
    prompt: 'When you picture the ultimate nature of reality, what feels truest?',
    multiSelect: false,
    options: [
      { id: 'one', label: 'A single, supreme God', contributions: [{ dimension: 'theism', option: 'monotheism', weight: 2 }] },
      { id: 'many', label: 'Many gods and goddesses', contributions: [{ dimension: 'theism', option: 'polytheism', weight: 2 }] },
      { id: 'one-of-many', label: 'One god I honor, among others that exist', contributions: [{ dimension: 'theism', option: 'henotheism', weight: 2 }] },
      { id: 'all-is-divine', label: 'The universe itself is divine', contributions: [{ dimension: 'theism', option: 'pantheism', weight: 1.5 }, { dimension: 'cosmology', option: 'monistic', weight: 1 }] },
      { id: 'beyond-and-within', label: 'A divine reality both within and beyond the world', contributions: [{ dimension: 'theism', option: 'panentheism', weight: 2 }] },
      { id: 'no-gods', label: 'No gods at all', contributions: [{ dimension: 'theism', option: 'nontheism', weight: 2 }, { dimension: 'divineNature', option: 'none', weight: 1 }] },
      { id: 'unknowable', label: 'Something unknown or unknowable', contributions: [{ dimension: 'theism', option: 'agnostic', weight: 2 }] },
    ],
  },
  {
    id: 'q_divine_personal',
    section: 'The Divine',
    prompt: 'Is the divine something you can have a personal relationship with?',
    multiSelect: false,
    options: [
      { id: 'personal', label: 'Yes — a personal being who hears me', contributions: [{ dimension: 'divineNature', option: 'personal', weight: 2 }] },
      { id: 'impersonal', label: 'No — an impersonal force, law, or ground of being', contributions: [{ dimension: 'divineNature', option: 'impersonal', weight: 2 }] },
      { id: 'both', label: 'Both — it has personal and impersonal faces', contributions: [{ dimension: 'divineNature', option: 'both', weight: 2 }] },
      { id: 'na', label: 'There is no divine being to relate to', contributions: [{ dimension: 'divineNature', option: 'none', weight: 2 }] },
    ],
  },
  {
    id: 'q_creator_involved',
    section: 'The Divine',
    prompt: 'If there is a creator, how involved is it in the world now?',
    multiSelect: false,
    options: [
      { id: 'active', label: 'Deeply involved and active in daily life', contributions: [{ dimension: 'divineNature', option: 'personal', weight: 1 }] },
      { id: 'distant', label: 'It set things in motion but does not intervene', contributions: [{ dimension: 'theism', option: 'deism', weight: 2 }] },
      { id: 'is-nature', label: 'It is simply the order of nature itself', contributions: [{ dimension: 'theism', option: 'pantheism', weight: 1 }, { dimension: 'authority', option: 'nature', weight: 1 }] },
      { id: 'no-creator', label: 'There is no creator', contributions: [{ dimension: 'theism', option: 'nontheism', weight: 1 }] },
    ],
  },
  {
    id: 'q_spirits_nature',
    section: 'The Divine',
    prompt: 'Do spirits or sacred presences dwell in nature, places, and objects?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — the world is alive with spirit', contributions: [{ dimension: 'theism', option: 'animism', weight: 2 }, { dimension: 'cosmology', option: 'animate', weight: 2 }] },
      { id: 'some', label: 'Perhaps, in a poetic or symbolic sense', contributions: [{ dimension: 'cosmology', option: 'animate', weight: 0.5 }] },
      { id: 'no', label: 'No — the natural world is not inhabited by spirits', contributions: [{ dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
    ],
  },
  {
    id: 'q_cosmic_struggle',
    section: 'The Divine',
    prompt: 'How do you understand the presence of good and evil?',
    multiSelect: false,
    options: [
      { id: 'two-powers', label: 'A real cosmic struggle between good and evil powers', contributions: [{ dimension: 'theism', option: 'dualism', weight: 2 }] },
      { id: 'one-source', label: 'All flows from one source; evil is absence or test', contributions: [{ dimension: 'theism', option: 'monotheism', weight: 0.5 }] },
      { id: 'karma', label: 'Consequence unfolds through cause and effect', contributions: [{ dimension: 'moralSource', option: 'karma', weight: 1.5 }] },
      { id: 'human', label: 'Good and evil are human, not cosmic, matters', contributions: [{ dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
    ],
  },
  {
    id: 'q_figures',
    section: 'The Divine',
    prompt: 'Which sacred figures, if any, draw you? (Choose any that resonate.)',
    helpText: 'Pick as many as feel meaningful, or none.',
    multiSelect: true,
    options: [
      { id: 'jesus', label: 'Jesus Christ', contributions: [{ dimension: 'keyFigures', option: 'jesus', weight: 2 }] },
      { id: 'muhammad', label: 'The Prophet Muhammad', contributions: [{ dimension: 'keyFigures', option: 'muhammad', weight: 2 }] },
      { id: 'hebrew', label: 'Moses & the Hebrew prophets', contributions: [{ dimension: 'keyFigures', option: 'hebrew-prophets', weight: 2 }] },
      { id: 'buddha', label: 'The Buddha', contributions: [{ dimension: 'keyFigures', option: 'buddha', weight: 2 }] },
      { id: 'hindu', label: 'Hindu deities (Vishnu, Shiva, Devi…)', contributions: [{ dimension: 'keyFigures', option: 'hindu-deities', weight: 2 }] },
      { id: 'nanak', label: 'Guru Nanak & the Sikh Gurus', contributions: [{ dimension: 'keyFigures', option: 'guru-nanak', weight: 2 }] },
      { id: 'mahavira', label: 'Mahavira & the Jain Tirthankaras', contributions: [{ dimension: 'keyFigures', option: 'mahavira', weight: 2 }] },
      { id: 'sages', label: 'Sages like Laozi or Confucius', contributions: [{ dimension: 'keyFigures', option: 'sages', weight: 2 }] },
      { id: 'zoroaster', label: 'Zarathustra', contributions: [{ dimension: 'keyFigures', option: 'zoroaster', weight: 2 }] },
      { id: 'bahaullah', label: 'Baháʼu’lláh / the Báb', contributions: [{ dimension: 'keyFigures', option: 'bahaullah', weight: 2 }] },
      { id: 'spirits', label: 'Orishas, loa, kami, or nature spirits', contributions: [{ dimension: 'keyFigures', option: 'spirits', weight: 2 }] },
      { id: 'ancestors', label: 'Ancestors and the departed', contributions: [{ dimension: 'keyFigures', option: 'ancestors', weight: 2 }] },
      { id: 'goddess', label: 'The Goddess / divine feminine', contributions: [{ dimension: 'keyFigures', option: 'goddess', weight: 2 }] },
      { id: 'guru', label: 'A living guru or teacher', contributions: [{ dimension: 'keyFigures', option: 'living-guru', weight: 2 }] },
      { id: 'self', label: 'The awakened self within', contributions: [{ dimension: 'keyFigures', option: 'self', weight: 2 }] },
      { id: 'none', label: 'No central figure', contributions: [{ dimension: 'keyFigures', option: 'none', weight: 2 }] },
    ],
  },
  {
    id: 'q_divine_feminine',
    section: 'The Divine',
    prompt: 'How important is the divine feminine or a Goddess to your spirituality?',
    multiSelect: false,
    options: [
      { id: 'central', label: 'Central — the sacred is strongly feminine', contributions: [{ dimension: 'keyFigures', option: 'goddess', weight: 2 }] },
      { id: 'balanced', label: 'One face of a divine beyond gender', contributions: [{ dimension: 'divineNature', option: 'impersonal', weight: 0.5 }] },
      { id: 'not', label: 'Not a significant theme for me', contributions: [] },
    ],
  },

  // ────────────────────────── Truth & Authority ──────────────────────────
  {
    id: 'q_authority',
    section: 'Truth & Authority',
    prompt: 'Where should religious truth ultimately come from? (Choose any that fit.)',
    multiSelect: true,
    options: [
      { id: 'scripture', label: 'Sacred scripture', contributions: [{ dimension: 'authority', option: 'scripture', weight: 2 }] },
      { id: 'clergy', label: 'An established clergy or institution', contributions: [{ dimension: 'authority', option: 'clergy', weight: 2 }, { dimension: 'community', option: 'hierarchical', weight: 1 }] },
      { id: 'experience', label: 'My own direct spiritual experience', contributions: [{ dimension: 'authority', option: 'personal-experience', weight: 2 }] },
      { id: 'reason', label: 'Reason and philosophy', contributions: [{ dimension: 'authority', option: 'reason', weight: 2 }, { dimension: 'moralSource', option: 'reason', weight: 1 }] },
      { id: 'tradition', label: 'Inherited tradition and custom', contributions: [{ dimension: 'authority', option: 'tradition', weight: 2 }] },
      { id: 'teacher', label: 'A living teacher, guru, or master', contributions: [{ dimension: 'authority', option: 'living-teacher', weight: 2 }, { dimension: 'keyFigures', option: 'living-guru', weight: 0.5 }] },
      { id: 'nature', label: 'Nature and the cosmos', contributions: [{ dimension: 'authority', option: 'nature', weight: 2 }] },
    ],
  },
  {
    id: 'q_scripture_reading',
    section: 'Truth & Authority',
    prompt: 'How should sacred texts be read?',
    multiSelect: false,
    options: [
      { id: 'literal', label: 'Literally — they are the inerrant word', contributions: [{ dimension: 'scriptureReading', option: 'literal', weight: 2 }, { dimension: 'reformStance', option: 'traditionalist', weight: 1 }] },
      { id: 'contextual', label: 'In historical and moral context', contributions: [{ dimension: 'scriptureReading', option: 'contextual', weight: 2 }] },
      { id: 'symbolic', label: 'As symbol, allegory, and mystical poetry', contributions: [{ dimension: 'scriptureReading', option: 'allegorical', weight: 2 }, { dimension: 'mysticism', option: 'present', weight: 0.5 }] },
      { id: 'none', label: 'I do not look to sacred texts much', contributions: [{ dimension: 'scriptureReading', option: 'non-scriptural', weight: 2 }] },
    ],
  },
  {
    id: 'q_one_true_path',
    section: 'Truth & Authority',
    prompt: 'Is there one true religion?',
    multiSelect: false,
    options: [
      { id: 'exclusive', label: 'Yes — one path is true, others are mistaken', contributions: [{ dimension: 'truthClaim', option: 'exclusive', weight: 2 }] },
      { id: 'inclusive', label: 'One path is fullest, but others hold real truth', contributions: [{ dimension: 'truthClaim', option: 'inclusive', weight: 2 }] },
      { id: 'pluralist', label: 'Many paths lead to the same summit', contributions: [{ dimension: 'truthClaim', option: 'pluralist', weight: 2 }] },
    ],
  },
  {
    id: 'q_reform',
    section: 'Truth & Authority',
    prompt: 'How should a tradition relate to the modern world?',
    multiSelect: false,
    options: [
      { id: 'traditional', label: 'Preserve inherited teaching as unchanged as possible', contributions: [{ dimension: 'reformStance', option: 'traditionalist', weight: 2 }] },
      { id: 'moderate', label: 'Hold the core, adapt the details', contributions: [{ dimension: 'reformStance', option: 'moderate', weight: 2 }] },
      { id: 'progressive', label: 'Actively reinterpret and reform for today', contributions: [{ dimension: 'reformStance', option: 'progressive', weight: 2 }] },
    ],
  },
  {
    id: 'q_certainty',
    section: 'Truth & Authority',
    prompt: 'How do you hold your beliefs?',
    multiSelect: false,
    options: [
      { id: 'certain', label: 'With firm conviction and certainty', contributions: [{ dimension: 'truthClaim', option: 'exclusive', weight: 1 }, { dimension: 'scriptureReading', option: 'literal', weight: 0.5 }] },
      { id: 'searching', label: 'As a sincere but open-ended search', contributions: [{ dimension: 'truthClaim', option: 'pluralist', weight: 1 }, { dimension: 'authority', option: 'personal-experience', weight: 0.5 }] },
      { id: 'skeptical', label: 'Provisionally, guided by evidence and doubt', contributions: [{ dimension: 'authority', option: 'reason', weight: 1.5 }, { dimension: 'theism', option: 'agnostic', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_revelation_ongoing',
    section: 'Truth & Authority',
    prompt: 'Is divine revelation finished, or still unfolding?',
    multiSelect: false,
    options: [
      { id: 'sealed', label: 'Complete — given fully in the past', contributions: [{ dimension: 'reformStance', option: 'traditionalist', weight: 1 }] },
      { id: 'progressive', label: 'Unfolding progressively across the ages', contributions: [{ dimension: 'keyFigures', option: 'bahaullah', weight: 0.5 }, { dimension: 'truthClaim', option: 'inclusive', weight: 0.5 }] },
      { id: 'personal', label: 'Available fresh to anyone, anytime', contributions: [{ dimension: 'authority', option: 'personal-experience', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_science_faith',
    section: 'Truth & Authority',
    prompt: 'How do faith and science relate for you?',
    multiSelect: false,
    options: [
      { id: 'faith-first', label: 'Where they conflict, revelation comes first', contributions: [{ dimension: 'scriptureReading', option: 'literal', weight: 1 }] },
      { id: 'harmony', label: 'They describe different, compatible truths', contributions: [{ dimension: 'scriptureReading', option: 'contextual', weight: 1 }] },
      { id: 'science-first', label: 'Empirical evidence should guide belief', contributions: [{ dimension: 'authority', option: 'reason', weight: 2 }, { dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
    ],
  },
  {
    id: 'q_mystery',
    section: 'Truth & Authority',
    prompt: 'How comfortable are you with mystery and paradox in belief?',
    multiSelect: false,
    options: [
      { id: 'embrace', label: 'I love mystery — truth is beyond words', contributions: [{ dimension: 'mysticism', option: 'central', weight: 1.5 }, { dimension: 'scriptureReading', option: 'allegorical', weight: 0.5 }] },
      { id: 'some', label: 'Some mystery, but I want clear teaching too', contributions: [{ dimension: 'mysticism', option: 'present', weight: 1 }] },
      { id: 'clarity', label: 'I prefer clear, definite answers', contributions: [{ dimension: 'mysticism', option: 'minimal', weight: 1 }, { dimension: 'authority', option: 'reason', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_prophets_many',
    section: 'Truth & Authority',
    prompt: 'How do you view the founders of other religions?',
    multiSelect: false,
    options: [
      { id: 'false', label: 'Only my tradition’s messengers are true', contributions: [{ dimension: 'truthClaim', option: 'exclusive', weight: 1.5 }] },
      { id: 'partial', label: 'They glimpsed part of a larger truth', contributions: [{ dimension: 'truthClaim', option: 'inclusive', weight: 1.5 }] },
      { id: 'all-valid', label: 'All were authentic teachers for their people', contributions: [{ dimension: 'truthClaim', option: 'pluralist', weight: 1.5 }] },
    ],
  },

  // ────────────────────────── Purpose & Afterlife ──────────────────────────
  {
    id: 'q_afterlife',
    section: 'Purpose & Afterlife',
    prompt: 'What do you believe happens after death?',
    multiSelect: false,
    options: [
      { id: 'heaven-hell', label: 'Judgment, then heaven or hell', contributions: [{ dimension: 'afterlife', option: 'heaven-hell', weight: 2 }, { dimension: 'cosmology', option: 'linear', weight: 1 }] },
      { id: 'reincarnation', label: 'Rebirth into another life', contributions: [{ dimension: 'afterlife', option: 'reincarnation', weight: 2 }, { dimension: 'cosmology', option: 'cyclical', weight: 1 }] },
      { id: 'liberation', label: 'Eventual release from the cycle of rebirth', contributions: [{ dimension: 'afterlife', option: 'liberation', weight: 2 }] },
      { id: 'union', label: 'Merging back into the divine', contributions: [{ dimension: 'afterlife', option: 'union-divine', weight: 2 }, { dimension: 'cosmology', option: 'monistic', weight: 0.5 }] },
      { id: 'ancestral', label: 'Joining the ancestors and spirit world', contributions: [{ dimension: 'afterlife', option: 'ancestral', weight: 2 }] },
      { id: 'nothing', label: 'Nothing — this life is all there is', contributions: [{ dimension: 'afterlife', option: 'none', weight: 2 }, { dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
      { id: 'unknown', label: 'I don’t know, and I’m at peace with that', contributions: [{ dimension: 'afterlife', option: 'uncertain', weight: 2 }] },
    ],
  },
  {
    id: 'q_salvation',
    section: 'Purpose & Afterlife',
    prompt: 'What most brings salvation, liberation, or wholeness? (Choose any.)',
    multiSelect: true,
    options: [
      { id: 'faith', label: 'Faith and divine grace', contributions: [{ dimension: 'salvationPath', option: 'faith-grace', weight: 2 }] },
      { id: 'works', label: 'Good deeds and ethical living', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 2 }] },
      { id: 'ritual', label: 'Faithful ritual and sacrament', contributions: [{ dimension: 'salvationPath', option: 'ritual', weight: 2 }] },
      { id: 'knowledge', label: 'Sacred knowledge or awakening insight', contributions: [{ dimension: 'salvationPath', option: 'knowledge', weight: 2 }] },
      { id: 'meditation', label: 'Meditation and inner discipline', contributions: [{ dimension: 'salvationPath', option: 'meditation', weight: 2 }] },
      { id: 'devotion', label: 'Loving devotion to the divine', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 2 }] },
      { id: 'cultivation', label: 'Cultivating virtue and harmony', contributions: [{ dimension: 'salvationPath', option: 'self-cultivation', weight: 2 }] },
      { id: 'none', label: 'I’m not focused on being “saved”', contributions: [{ dimension: 'salvationPath', option: 'not-central', weight: 2 }] },
    ],
  },
  {
    id: 'q_lifes_purpose',
    section: 'Purpose & Afterlife',
    prompt: 'What is the deepest purpose of human life?',
    multiSelect: false,
    options: [
      { id: 'know-god', label: 'To know, love, and serve God', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 1 }, { dimension: 'divineNature', option: 'personal', weight: 0.5 }] },
      { id: 'liberation', label: 'To awaken and be freed from suffering', contributions: [{ dimension: 'salvationPath', option: 'meditation', weight: 1 }, { dimension: 'afterlife', option: 'liberation', weight: 1 }] },
      { id: 'harmony', label: 'To live in harmony with the natural order', contributions: [{ dimension: 'moralSource', option: 'harmony', weight: 1.5 }, { dimension: 'salvationPath', option: 'self-cultivation', weight: 1 }] },
      { id: 'good-life', label: 'To flourish and do good in this one life', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 1 }, { dimension: 'moralSource', option: 'reason', weight: 1 }] },
      { id: 'no-fixed', label: 'There is no fixed purpose; we make our own', contributions: [{ dimension: 'salvationPath', option: 'not-central', weight: 1 }, { dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
    ],
  },
  {
    id: 'q_time_shape',
    section: 'Purpose & Afterlife',
    prompt: 'What is the shape of time and the cosmos?',
    multiSelect: false,
    options: [
      { id: 'linear', label: 'A story with a beginning and a final end', contributions: [{ dimension: 'cosmology', option: 'linear', weight: 2 }] },
      { id: 'cyclical', label: 'Vast repeating cycles of ages', contributions: [{ dimension: 'cosmology', option: 'cyclical', weight: 2 }] },
      { id: 'oneness', label: 'All apparent reality is ultimately one', contributions: [{ dimension: 'cosmology', option: 'monistic', weight: 2 }] },
      { id: 'natural', label: 'A natural universe without a plan', contributions: [{ dimension: 'cosmology', option: 'naturalistic', weight: 2 }] },
      { id: 'alive', label: 'A living web of spirit and relationship', contributions: [{ dimension: 'cosmology', option: 'animate', weight: 2 }] },
    ],
  },
  {
    id: 'q_suffering',
    section: 'Purpose & Afterlife',
    prompt: 'Why do people suffer?',
    multiSelect: false,
    options: [
      { id: 'test', label: 'A test or part of God’s larger plan', contributions: [{ dimension: 'moralSource', option: 'divine-command', weight: 1 }] },
      { id: 'karma', label: 'The working-out of past actions (karma)', contributions: [{ dimension: 'moralSource', option: 'karma', weight: 2 }] },
      { id: 'attachment', label: 'Attachment and craving we can release', contributions: [{ dimension: 'salvationPath', option: 'meditation', weight: 1 }, { dimension: 'worldStance', option: 'ascetic', weight: 0.5 }] },
      { id: 'natural', label: 'Simply part of a natural, indifferent world', contributions: [{ dimension: 'cosmology', option: 'naturalistic', weight: 1 }] },
    ],
  },
  {
    id: 'q_moral_source',
    section: 'Purpose & Afterlife',
    prompt: 'What ultimately makes something right or wrong?',
    multiSelect: false,
    options: [
      { id: 'command', label: 'The commands of God', contributions: [{ dimension: 'moralSource', option: 'divine-command', weight: 2 }] },
      { id: 'karma', label: 'The law of cause, effect, and karma', contributions: [{ dimension: 'moralSource', option: 'karma', weight: 2 }] },
      { id: 'natural-law', label: 'A built-in moral order to reality', contributions: [{ dimension: 'moralSource', option: 'natural-law', weight: 2 }] },
      { id: 'harmony', label: 'What preserves harmony and balance', contributions: [{ dimension: 'moralSource', option: 'harmony', weight: 2 }] },
      { id: 'reason', label: 'Human reason and empathy', contributions: [{ dimension: 'moralSource', option: 'reason', weight: 2 }] },
      { id: 'compassion', label: 'Compassion for all sentient beings', contributions: [{ dimension: 'moralSource', option: 'compassion', weight: 2 }] },
    ],
  },
  {
    id: 'q_salvation_scope',
    section: 'Purpose & Afterlife',
    prompt: 'Who can attain the ultimate goal (heaven, liberation, etc.)?',
    multiSelect: false,
    options: [
      { id: 'believers', label: 'Chiefly those within the true faith', contributions: [{ dimension: 'truthClaim', option: 'exclusive', weight: 1 }] },
      { id: 'good-people', label: 'Anyone who lives rightly, whatever their creed', contributions: [{ dimension: 'truthClaim', option: 'pluralist', weight: 1 }, { dimension: 'salvationPath', option: 'good-works', weight: 0.5 }] },
      { id: 'all-eventually', label: 'Everyone, eventually — none are lost forever', contributions: [{ dimension: 'truthClaim', option: 'inclusive', weight: 1 }] },
    ],
  },
  {
    id: 'q_grace_effort',
    section: 'Purpose & Afterlife',
    prompt: 'Do we reach the goal by our own effort or by a gift from beyond?',
    multiSelect: false,
    options: [
      { id: 'grace', label: 'By grace — it is freely given', contributions: [{ dimension: 'salvationPath', option: 'faith-grace', weight: 2 }] },
      { id: 'effort', label: 'By disciplined effort and practice', contributions: [{ dimension: 'salvationPath', option: 'meditation', weight: 1 }, { dimension: 'worldStance', option: 'ascetic', weight: 0.5 }] },
      { id: 'both', label: 'Effort meets grace partway', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 0.5 }, { dimension: 'salvationPath', option: 'good-works', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_sacred_history',
    section: 'Purpose & Afterlife',
    prompt: 'Which resonates more with your sense of the sacred past?',
    multiSelect: false,
    options: [
      { id: 'ancient', label: 'Timeless, ancient, pre-historic wisdom', contributions: [{ dimension: 'era', option: 'ancient', weight: 1.5 }] },
      { id: 'classical', label: 'The great classical founders and scriptures', contributions: [{ dimension: 'era', option: 'classical', weight: 1.5 }] },
      { id: 'modern', label: 'A fresh, modern spiritual movement', contributions: [{ dimension: 'era', option: 'modern', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_evil_redeemable',
    section: 'Purpose & Afterlife',
    prompt: 'How central is the idea of sin and redemption to you?',
    multiSelect: false,
    options: [
      { id: 'central', label: 'Very — we need saving from sin', contributions: [{ dimension: 'salvationPath', option: 'faith-grace', weight: 1 }, { dimension: 'afterlife', option: 'heaven-hell', weight: 0.5 }] },
      { id: 'growth', label: 'It’s more about growth than guilt', contributions: [{ dimension: 'salvationPath', option: 'self-cultivation', weight: 1 }] },
      { id: 'not', label: 'Sin isn’t really my framework', contributions: [{ dimension: 'salvationPath', option: 'not-central', weight: 1 }] },
    ],
  },

  // ────────────────────────── Practice & Community ──────────────────────────
  {
    id: 'q_ritual',
    section: 'Practice & Community',
    prompt: 'How much do you want ritual and ceremony in your practice?',
    multiSelect: false,
    options: [
      { id: 'rich', label: 'Rich, frequent ritual and liturgy', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 2 }] },
      { id: 'some', label: 'Some meaningful regular ritual', contributions: [{ dimension: 'ritualIntensity', option: 'moderate', weight: 2 }] },
      { id: 'simple', label: 'Simple and stripped-down', contributions: [{ dimension: 'ritualIntensity', option: 'low', weight: 2 }] },
      { id: 'none', label: 'Little or no formal ritual', contributions: [{ dimension: 'ritualIntensity', option: 'none', weight: 2 }] },
    ],
  },
  {
    id: 'q_community_shape',
    section: 'Practice & Community',
    prompt: 'What community structure appeals to you most?',
    multiSelect: false,
    options: [
      { id: 'hierarchy', label: 'An established hierarchy with clergy', contributions: [{ dimension: 'community', option: 'hierarchical', weight: 2 }] },
      { id: 'congregation', label: 'Self-governing local congregations', contributions: [{ dimension: 'community', option: 'congregational', weight: 2 }] },
      { id: 'loose', label: 'A loose, decentralized network', contributions: [{ dimension: 'community', option: 'decentralized', weight: 2 }] },
      { id: 'monastic', label: 'Monastic orders and dedicated communities', contributions: [{ dimension: 'community', option: 'monastic', weight: 2 }] },
      { id: 'solo', label: 'Mostly a solitary, personal practice', contributions: [{ dimension: 'community', option: 'solitary', weight: 2 }] },
    ],
  },
  {
    id: 'q_mysticism',
    section: 'Practice & Community',
    prompt: 'How drawn are you to mystical, contemplative union with the sacred?',
    multiSelect: false,
    options: [
      { id: 'core', label: 'It’s the very heart of the path for me', contributions: [{ dimension: 'mysticism', option: 'central', weight: 2 }] },
      { id: 'part', label: 'A valued part of a broader life', contributions: [{ dimension: 'mysticism', option: 'present', weight: 2 }] },
      { id: 'little', label: 'Not really my emphasis', contributions: [{ dimension: 'mysticism', option: 'minimal', weight: 2 }] },
    ],
  },
  {
    id: 'q_worldliness',
    section: 'Practice & Community',
    prompt: 'What is the healthiest attitude toward the body and worldly pleasure?',
    multiSelect: false,
    options: [
      { id: 'embrace', label: 'Embrace and enjoy the goodness of the world', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 2 }] },
      { id: 'middle', label: 'A balanced middle way', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 2 }] },
      { id: 'discipline', label: 'Discipline or renounce desire', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 2 }] },
    ],
  },
  {
    id: 'q_rules',
    section: 'Practice & Community',
    prompt: 'How much should religion govern daily life — diet, dress, schedule, law?',
    multiSelect: false,
    options: [
      { id: 'comprehensive', label: 'A comprehensive code for all of life', contributions: [{ dimension: 'lawInDailyLife', option: 'comprehensive', weight: 2 }] },
      { id: 'some', label: 'Some guidelines, broadly applied', contributions: [{ dimension: 'lawInDailyLife', option: 'moderate', weight: 2 }] },
      { id: 'few', label: 'Few fixed rules; conscience leads', contributions: [{ dimension: 'lawInDailyLife', option: 'minimal', weight: 2 }] },
    ],
  },
  {
    id: 'q_prayer_style',
    section: 'Practice & Community',
    prompt: 'Which spiritual practices call to you? (Choose any.)',
    multiSelect: true,
    options: [
      { id: 'prayer', label: 'Prayer to a personal God', contributions: [{ dimension: 'divineNature', option: 'personal', weight: 1 }, { dimension: 'salvationPath', option: 'devotion', weight: 0.5 }] },
      { id: 'meditation', label: 'Silent meditation', contributions: [{ dimension: 'salvationPath', option: 'meditation', weight: 1.5 }, { dimension: 'mysticism', option: 'present', weight: 0.5 }] },
      { id: 'chant', label: 'Chanting, mantra, or sacred song', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 1 }, { dimension: 'ritualIntensity', option: 'moderate', weight: 0.5 }] },
      { id: 'liturgy', label: 'Formal liturgy and sacraments', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 1.5 }, { dimension: 'salvationPath', option: 'ritual', weight: 0.5 }] },
      { id: 'service', label: 'Acts of service and justice', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 1.5 }] },
      { id: 'nature', label: 'Ritual in and with nature', contributions: [{ dimension: 'authority', option: 'nature', weight: 1 }, { dimension: 'cosmology', option: 'animate', weight: 0.5 }] },
      { id: 'study', label: 'Study of texts and philosophy', contributions: [{ dimension: 'authority', option: 'scripture', weight: 0.5 }, { dimension: 'authority', option: 'reason', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_leadership',
    section: 'Practice & Community',
    prompt: 'Who should lead a religious community?',
    multiSelect: false,
    options: [
      { id: 'ordained', label: 'Ordained, trained clergy in a lineage', contributions: [{ dimension: 'community', option: 'hierarchical', weight: 1.5 }, { dimension: 'authority', option: 'clergy', weight: 1 }] },
      { id: 'guru', label: 'A realized spiritual master or guru', contributions: [{ dimension: 'authority', option: 'living-teacher', weight: 1.5 }] },
      { id: 'elected', label: 'Elders or leaders chosen by the community', contributions: [{ dimension: 'community', option: 'congregational', weight: 1.5 }] },
      { id: 'none', label: 'No formal leaders — we’re equals', contributions: [{ dimension: 'community', option: 'decentralized', weight: 1.5 }, { dimension: 'genderRoles', option: 'egalitarian', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_initiation',
    section: 'Practice & Community',
    prompt: 'How does one enter the tradition?',
    multiSelect: false,
    options: [
      { id: 'open', label: 'Open to anyone who chooses it', contributions: [{ dimension: 'scope', option: 'universal', weight: 2 }] },
      { id: 'born', label: 'Mainly born into a people or culture', contributions: [{ dimension: 'scope', option: 'ethnic', weight: 2 }] },
      { id: 'initiation', label: 'Through initiation and secret teaching', contributions: [{ dimension: 'scope', option: 'initiatory', weight: 2 }, { dimension: 'community', option: 'decentralized', weight: 0.3 }] },
    ],
  },
  {
    id: 'q_proselytize',
    section: 'Practice & Community',
    prompt: 'Should a faith actively seek converts?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — spreading the message matters', contributions: [{ dimension: 'proselytizing', option: 'active', weight: 2 }] },
      { id: 'welcome', label: 'Welcome newcomers, but don’t pursue them', contributions: [{ dimension: 'proselytizing', option: 'welcoming', weight: 2 }] },
      { id: 'no', label: 'No — it’s a private, personal matter', contributions: [{ dimension: 'proselytizing', option: 'non-proselytizing', weight: 2 }] },
      { id: 'closed', label: 'It should stay within its born community', contributions: [{ dimension: 'proselytizing', option: 'closed', weight: 2 }, { dimension: 'scope', option: 'ethnic', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_sacred_space',
    section: 'Practice & Community',
    prompt: 'Where do you most feel the sacred?',
    multiSelect: false,
    options: [
      { id: 'temple', label: 'In a temple, church, or house of worship', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 0.8 }, { dimension: 'community', option: 'hierarchical', weight: 0.3 }] },
      { id: 'nature', label: 'Outdoors, in the natural world', contributions: [{ dimension: 'authority', option: 'nature', weight: 1.5 }, { dimension: 'cosmology', option: 'animate', weight: 0.5 }] },
      { id: 'within', label: 'Within, in silence and stillness', contributions: [{ dimension: 'mysticism', option: 'central', weight: 1 }, { dimension: 'community', option: 'solitary', weight: 0.5 }] },
      { id: 'home', label: 'At home, with family and ancestors', contributions: [{ dimension: 'afterlife', option: 'ancestral', weight: 0.8 }, { dimension: 'keyFigures', option: 'ancestors', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_calendar',
    section: 'Practice & Community',
    prompt: 'How appealing is a life shaped by sacred seasons and festivals?',
    multiSelect: false,
    options: [
      { id: 'love', label: 'Very — I want a rich festival calendar', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 1 }, { dimension: 'authority', option: 'tradition', weight: 0.5 }] },
      { id: 'some', label: 'A few meaningful holy days', contributions: [{ dimension: 'ritualIntensity', option: 'moderate', weight: 1 }] },
      { id: 'none', label: 'I don’t need a religious calendar', contributions: [{ dimension: 'ritualIntensity', option: 'low', weight: 1 }] },
    ],
  },
  {
    id: 'q_ascetic_practice',
    section: 'Practice & Community',
    prompt: 'How do you feel about fasting, celibacy, or renunciation as a spiritual path?',
    multiSelect: false,
    options: [
      { id: 'inspiring', label: 'Inspiring — renunciation frees the spirit', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 2 }, { dimension: 'community', option: 'monastic', weight: 0.5 }] },
      { id: 'occasional', label: 'Good in measured, occasional doses', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 1 }] },
      { id: 'no', label: 'Not for me — life is to be enjoyed', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 1.5 }] },
    ],
  },

  // ─────────────────────── Ethics, Society & Style ───────────────────────
  {
    id: 'q_gender',
    section: 'Ethics, Society & Style',
    prompt: 'What role should gender play in religious life and leadership?',
    multiSelect: false,
    options: [
      { id: 'equal', label: 'Fully equal roles for all genders', contributions: [{ dimension: 'genderRoles', option: 'egalitarian', weight: 2 }] },
      { id: 'complementary', label: 'Distinct but equally honored roles', contributions: [{ dimension: 'genderRoles', option: 'complementarian', weight: 2 }] },
      { id: 'traditional', label: 'Traditional, established gender roles', contributions: [{ dimension: 'genderRoles', option: 'traditional', weight: 2 }] },
    ],
  },
  {
    id: 'q_social_justice',
    section: 'Ethics, Society & Style',
    prompt: 'How important is social justice and care for the marginalized to your ideal faith?',
    multiSelect: false,
    options: [
      { id: 'central', label: 'Central — faith must transform society', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 1.5 }, { dimension: 'reformStance', option: 'progressive', weight: 1 }] },
      { id: 'important', label: 'Important, alongside personal devotion', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 0.8 }] },
      { id: 'personal', label: 'Faith is more about the inner and eternal', contributions: [{ dimension: 'mysticism', option: 'present', weight: 0.5 }, { dimension: 'worldStance', option: 'ascetic', weight: 0.3 }] },
    ],
  },
  {
    id: 'q_animals',
    section: 'Ethics, Society & Style',
    prompt: 'What do you believe about our duty to animals and all living things?',
    multiSelect: false,
    options: [
      { id: 'ahimsa', label: 'Non-harm to all beings is essential (even vegetarian)', contributions: [{ dimension: 'moralSource', option: 'compassion', weight: 1.5 }, { dimension: 'keyFigures', option: 'mahavira', weight: 0.3 }] },
      { id: 'stewards', label: 'We are stewards meant to care for creation', contributions: [{ dimension: 'moralSource', option: 'divine-command', weight: 0.5 }, { dimension: 'moralSource', option: 'natural-law', weight: 0.5 }] },
      { id: 'kinship', label: 'Animals and land are our kin and relations', contributions: [{ dimension: 'cosmology', option: 'animate', weight: 1 }, { dimension: 'moralSource', option: 'harmony', weight: 1 }] },
      { id: 'human-first', label: 'Human welfare comes first', contributions: [{ dimension: 'moralSource', option: 'reason', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_wealth',
    section: 'Ethics, Society & Style',
    prompt: 'How should a spiritual life relate to money and success?',
    multiSelect: false,
    options: [
      { id: 'blessing', label: 'Prosperity can be a blessing to enjoy and share', contributions: [{ dimension: 'worldStance', option: 'affirming', weight: 1 }] },
      { id: 'detach', label: 'Hold it lightly; simplicity is freeing', contributions: [{ dimension: 'worldStance', option: 'balanced', weight: 1 }] },
      { id: 'renounce', label: 'True seekers give it up', contributions: [{ dimension: 'worldStance', option: 'ascetic', weight: 1.5 }] },
    ],
  },
  {
    id: 'q_group_size',
    section: 'Ethics, Society & Style',
    prompt: 'Does the size or age of a tradition matter to you?',
    multiSelect: false,
    options: [
      { id: 'ancient-big', label: 'I want deep roots and a long lineage', contributions: [{ dimension: 'era', option: 'classical', weight: 1 }, { dimension: 'reformStance', option: 'traditionalist', weight: 0.5 }] },
      { id: 'small-close', label: 'A small, close-knit community appeals to me', contributions: [{ dimension: 'community', option: 'congregational', weight: 0.5 }, { dimension: 'scope', option: 'initiatory', weight: 0.5 }] },
      { id: 'new-fresh', label: 'I’m open to a new or emerging movement', contributions: [{ dimension: 'era', option: 'modern', weight: 1.5 }] },
      { id: 'dontcare', label: 'Size and age don’t matter to me', contributions: [] },
    ],
  },
  {
    id: 'q_conversion_openness',
    section: 'Ethics, Society & Style',
    prompt: 'How do you feel about traditions that keep teachings secret or restricted?',
    multiSelect: false,
    options: [
      { id: 'drawn', label: 'Drawn to it — depth is earned through initiation', contributions: [{ dimension: 'scope', option: 'initiatory', weight: 1.5 }, { dimension: 'mysticism', option: 'central', weight: 0.5 }] },
      { id: 'neutral', label: 'Neutral — some mystery is fine', contributions: [] },
      { id: 'prefer-open', label: 'I prefer everything open and transparent', contributions: [{ dimension: 'scope', option: 'universal', weight: 1 }, { dimension: 'authority', option: 'reason', weight: 0.3 }] },
    ],
  },
  {
    id: 'q_style',
    section: 'Ethics, Society & Style',
    prompt: 'Which worship atmosphere feels most like home?',
    multiSelect: false,
    options: [
      { id: 'solemn', label: 'Solemn, ancient, and reverent', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 1 }, { dimension: 'reformStance', option: 'traditionalist', weight: 0.5 }] },
      { id: 'joyful', label: 'Joyful, expressive, and ecstatic', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 1 }, { dimension: 'mysticism', option: 'present', weight: 0.5 }] },
      { id: 'quiet', label: 'Quiet, simple, and contemplative', contributions: [{ dimension: 'ritualIntensity', option: 'low', weight: 1 }, { dimension: 'mysticism', option: 'central', weight: 0.5 }] },
      { id: 'intellectual', label: 'Thoughtful, discussion-based, and questioning', contributions: [{ dimension: 'authority', option: 'reason', weight: 1 }, { dimension: 'reformStance', option: 'progressive', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_god_law_state',
    section: 'Ethics, Society & Style',
    prompt: 'Should religious teaching shape law and public life?',
    multiSelect: false,
    options: [
      { id: 'yes', label: 'Yes — faith should guide society and law', contributions: [{ dimension: 'lawInDailyLife', option: 'comprehensive', weight: 1 }, { dimension: 'reformStance', option: 'traditionalist', weight: 0.5 }] },
      { id: 'values', label: 'Its values can inform, but not dictate, law', contributions: [{ dimension: 'lawInDailyLife', option: 'moderate', weight: 1 }] },
      { id: 'separate', label: 'Faith and public law should stay separate', contributions: [{ dimension: 'lawInDailyLife', option: 'minimal', weight: 1 }, { dimension: 'reformStance', option: 'progressive', weight: 0.5 }] },
    ],
  },
  {
    id: 'q_identity',
    section: 'Ethics, Society & Style',
    prompt: 'How should a faith relate to a particular people or heritage?',
    multiSelect: false,
    options: [
      { id: 'universal', label: 'It should transcend all ethnic lines', contributions: [{ dimension: 'scope', option: 'universal', weight: 1.5 }, { dimension: 'proselytizing', option: 'welcoming', weight: 0.3 }] },
      { id: 'rooted', label: 'It’s beautifully woven into a specific culture', contributions: [{ dimension: 'scope', option: 'ethnic', weight: 1.5 }, { dimension: 'proselytizing', option: 'closed', weight: 0.3 }] },
      { id: 'either', label: 'Either can be authentic', contributions: [] },
    ],
  },
  {
    id: 'q_after_all',
    section: 'Ethics, Society & Style',
    prompt: 'Finally — which best captures your spiritual temperament?',
    multiSelect: true,
    options: [
      { id: 'devotional', label: 'Devotional — I love with the heart', contributions: [{ dimension: 'salvationPath', option: 'devotion', weight: 1 }, { dimension: 'divineNature', option: 'personal', weight: 0.5 }] },
      { id: 'contemplative', label: 'Contemplative — I seek in silence', contributions: [{ dimension: 'mysticism', option: 'central', weight: 1 }, { dimension: 'salvationPath', option: 'meditation', weight: 0.5 }] },
      { id: 'ethical', label: 'Ethical — I serve and do good', contributions: [{ dimension: 'salvationPath', option: 'good-works', weight: 1 }, { dimension: 'moralSource', option: 'reason', weight: 0.5 }] },
      { id: 'intellectual', label: 'Philosophical — I reason and question', contributions: [{ dimension: 'authority', option: 'reason', weight: 1 }] },
      { id: 'ritual', label: 'Ceremonial — I love sacred form and ritual', contributions: [{ dimension: 'ritualIntensity', option: 'high', weight: 1 }, { dimension: 'salvationPath', option: 'ritual', weight: 0.5 }] },
      { id: 'earthy', label: 'Earthy — I feel the sacred in nature', contributions: [{ dimension: 'authority', option: 'nature', weight: 1 }, { dimension: 'cosmology', option: 'animate', weight: 0.5 }] },
      { id: 'ancestral', label: 'Ancestral — I honor those who came before', contributions: [{ dimension: 'keyFigures', option: 'ancestors', weight: 1 }, { dimension: 'afterlife', option: 'ancestral', weight: 0.5 }] },
    ],
  },

  // ─────────────────── Meaning, Ethics & Temperament ───────────────────
  {
    id: 'q_ethical_focus',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'When you picture living well, where does most of your moral energy go?',
    multiSelect: false,
    options: [
      { id: 'self', label: 'Mastering and perfecting myself', contributions: [{ dimension: 'ethicalFocus', option: 'self-mastery', weight: 2 }] },
      { id: 'family', label: 'Duty to my family and community', contributions: [{ dimension: 'ethicalFocus', option: 'family-community', weight: 2 }] },
      { id: 'justice', label: 'Justice for the vulnerable and society', contributions: [{ dimension: 'ethicalFocus', option: 'social-justice', weight: 2 }] },
      { id: 'all', label: 'The welfare of all living beings', contributions: [{ dimension: 'ethicalFocus', option: 'all-beings', weight: 2 }] },
      { id: 'divine', label: 'Devotion and service to the divine', contributions: [{ dimension: 'ethicalFocus', option: 'devotion-divine', weight: 2 }] },
    ],
  },
  {
    id: 'q_meaning_source',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'Where does life’s meaning ultimately come from?',
    multiSelect: false,
    options: [
      { id: 'divine', label: 'A divine plan or God’s will', contributions: [{ dimension: 'meaningSource', option: 'divine-plan', weight: 2 }, { dimension: 'divineNature', option: 'personal', weight: 0.3 }] },
      { id: 'cosmic', label: 'A cosmic order to align with (dharma, the Tao)', contributions: [{ dimension: 'meaningSource', option: 'cosmic-order', weight: 2 }, { dimension: 'moralSource', option: 'harmony', weight: 0.3 }] },
      { id: 'self', label: 'Meaning I create for myself', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 2 }] },
      { id: 'love', label: 'Love, relationships, and community', contributions: [{ dimension: 'meaningSource', option: 'relationships', weight: 2 }] },
      { id: 'none', label: 'There is no inherent meaning — and that’s okay', contributions: [{ dimension: 'meaningSource', option: 'none-and-ok', weight: 2 }, { dimension: 'salvationPath', option: 'not-central', weight: 0.3 }] },
    ],
  },
  {
    id: 'q_desire_stance',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'What is the ideal relationship with desire and strong emotion?',
    multiSelect: false,
    options: [
      { id: 'transcend', label: 'Extinguish craving and transcend desire', contributions: [{ dimension: 'desireStance', option: 'transcend', weight: 2 }, { dimension: 'worldStance', option: 'ascetic', weight: 0.4 }] },
      { id: 'master', label: 'Master and discipline the passions', contributions: [{ dimension: 'desireStance', option: 'master', weight: 2 }, { dimension: 'ethicalFocus', option: 'self-mastery', weight: 0.4 }] },
      { id: 'moderate', label: 'Enjoy desire in balanced moderation', contributions: [{ dimension: 'desireStance', option: 'moderate', weight: 2 }, { dimension: 'worldStance', option: 'balanced', weight: 0.4 }] },
      { id: 'embrace', label: 'Fully embrace desire and feeling', contributions: [{ dimension: 'desireStance', option: 'embrace', weight: 2 }, { dimension: 'worldStance', option: 'affirming', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_good_life',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'Which vision of “the good life” pulls at you most?',
    multiSelect: false,
    options: [
      { id: 'epicurean', label: 'Tranquil pleasure, friendship, and freedom from fear', contributions: [{ dimension: 'desireStance', option: 'moderate', weight: 1 }, { dimension: 'worldStance', option: 'affirming', weight: 1 }, { dimension: 'meaningSource', option: 'self-created', weight: 0.5 }] },
      { id: 'stoic', label: 'Virtue, self-command, and serenity whatever comes', contributions: [{ dimension: 'ethicalFocus', option: 'self-mastery', weight: 1 }, { dimension: 'desireStance', option: 'master', weight: 1 }, { dimension: 'moralSource', option: 'natural-law', weight: 0.5 }] },
      { id: 'altruist', label: 'Doing the most good and reducing suffering', contributions: [{ dimension: 'ethicalFocus', option: 'all-beings', weight: 1 }, { dimension: 'moralSource', option: 'compassion', weight: 0.7 }, { dimension: 'salvationPath', option: 'good-works', weight: 0.5 }] },
      { id: 'contemplative', label: 'Rising above it all into stillness and insight', contributions: [{ dimension: 'desireStance', option: 'transcend', weight: 1 }, { dimension: 'worldStance', option: 'ascetic', weight: 1 }, { dimension: 'mysticism', option: 'central', weight: 0.5 }] },
      { id: 'devotional', label: 'Union with and surrender to the divine', contributions: [{ dimension: 'ethicalFocus', option: 'devotion-divine', weight: 1 }, { dimension: 'salvationPath', option: 'devotion', weight: 0.7 }] },
    ],
  },
  {
    id: 'q_future_progress',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'How do you feel about the future and human progress?',
    multiSelect: false,
    options: [
      { id: 'transhuman', label: 'Science and technology can transform the human condition', contributions: [{ dimension: 'era', option: 'modern', weight: 1 }, { dimension: 'reformStance', option: 'progressive', weight: 1 }, { dimension: 'authority', option: 'reason', weight: 0.5 }] },
      { id: 'restore', label: 'We should return to timeless, ancient wisdom', contributions: [{ dimension: 'reformStance', option: 'traditionalist', weight: 1.5 }, { dimension: 'era', option: 'ancient', weight: 0.7 }, { dimension: 'meaningSource', option: 'cosmic-order', weight: 0.5 }] },
      { id: 'reform', label: 'Steady reform toward a more just world', contributions: [{ dimension: 'reformStance', option: 'progressive', weight: 1 }, { dimension: 'ethicalFocus', option: 'social-justice', weight: 1 }] },
      { id: 'harmony', label: 'Live simply, in harmony with nature', contributions: [{ dimension: 'authority', option: 'nature', weight: 1 }, { dimension: 'ethicalFocus', option: 'all-beings', weight: 0.7 }, { dimension: 'worldStance', option: 'ascetic', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_test_truth',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'When you want to know what’s really true, what do you trust most?',
    multiSelect: false,
    options: [
      { id: 'scripture', label: 'Sacred scripture', contributions: [{ dimension: 'scriptureReading', option: 'literal', weight: 1 }, { dimension: 'authority', option: 'scripture', weight: 1 }] },
      { id: 'reason', label: 'Reason, evidence, and science', contributions: [{ dimension: 'authority', option: 'reason', weight: 1.5 }, { dimension: 'cosmology', option: 'naturalistic', weight: 0.6 }] },
      { id: 'experience', label: 'Direct inner experience', contributions: [{ dimension: 'authority', option: 'personal-experience', weight: 1.5 }, { dimension: 'mysticism', option: 'present', weight: 0.4 }] },
      { id: 'tradition', label: 'Trusted teachers and inherited tradition', contributions: [{ dimension: 'authority', option: 'tradition', weight: 1 }, { dimension: 'scriptureReading', option: 'contextual', weight: 0.4 }] },
    ],
  },
  {
    id: 'q_daily_rules',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'How much should your beliefs shape daily habits — food, dress, time, relationships?',
    multiSelect: false,
    options: [
      { id: 'comprehensive', label: 'A detailed code covering most of daily life', contributions: [{ dimension: 'lawInDailyLife', option: 'comprehensive', weight: 2 }] },
      { id: 'moderate', label: 'Some meaningful practices and guidelines', contributions: [{ dimension: 'lawInDailyLife', option: 'moderate', weight: 2 }] },
      { id: 'minimal', label: 'Few fixed rules — conscience and context lead', contributions: [{ dimension: 'lawInDailyLife', option: 'minimal', weight: 2 }] },
    ],
  },
  {
    id: 'q_gender_leadership',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'What feels right for gender and leadership in a community you’d join?',
    multiSelect: false,
    options: [
      { id: 'equal', label: 'Fully equal roles and leadership for all genders', contributions: [{ dimension: 'genderRoles', option: 'egalitarian', weight: 2 }] },
      { id: 'complementary', label: 'Distinct but equally honored roles', contributions: [{ dimension: 'genderRoles', option: 'complementarian', weight: 2 }] },
      { id: 'traditional', label: 'Traditional, established gender roles', contributions: [{ dimension: 'genderRoles', option: 'traditional', weight: 2 }] },
    ],
  },
  {
    id: 'q_outsiders',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'How should your path relate to outsiders?',
    multiSelect: false,
    options: [
      { id: 'active', label: 'Actively share the message and invite everyone', contributions: [{ dimension: 'proselytizing', option: 'active', weight: 2 }, { dimension: 'scope', option: 'universal', weight: 0.6 }] },
      { id: 'welcome', label: 'Open to any sincere seeker, but not pushy', contributions: [{ dimension: 'proselytizing', option: 'welcoming', weight: 2 }, { dimension: 'scope', option: 'universal', weight: 0.4 }] },
      { id: 'private', label: 'A private path — not something to spread', contributions: [{ dimension: 'proselytizing', option: 'non-proselytizing', weight: 2 }] },
      { id: 'closed', label: 'Held within a people or through initiation', contributions: [{ dimension: 'proselytizing', option: 'closed', weight: 2 }, { dimension: 'scope', option: 'initiatory', weight: 0.6 }] },
    ],
  },
  {
    id: 'q_meaning_sources_multi',
    section: 'Meaning, Ethics & Temperament',
    prompt: 'Which of these most give your life meaning? (Choose any.)',
    multiSelect: true,
    options: [
      { id: 'god', label: 'Knowing and serving the divine', contributions: [{ dimension: 'meaningSource', option: 'divine-plan', weight: 1 }, { dimension: 'ethicalFocus', option: 'devotion-divine', weight: 0.6 }] },
      { id: 'order', label: 'Aligning with a larger cosmic order', contributions: [{ dimension: 'meaningSource', option: 'cosmic-order', weight: 1 }] },
      { id: 'self', label: 'Forging my own path and projects', contributions: [{ dimension: 'meaningSource', option: 'self-created', weight: 1 }] },
      { id: 'love', label: 'Love, family, and friendship', contributions: [{ dimension: 'meaningSource', option: 'relationships', weight: 1 }, { dimension: 'ethicalFocus', option: 'family-community', weight: 0.5 }] },
      { id: 'better', label: 'Leaving the world better than I found it', contributions: [{ dimension: 'ethicalFocus', option: 'social-justice', weight: 0.8 }, { dimension: 'salvationPath', option: 'good-works', weight: 0.5 }] },
      { id: 'truth', label: 'The pursuit of knowledge and truth', contributions: [{ dimension: 'authority', option: 'reason', weight: 0.7 }, { dimension: 'salvationPath', option: 'knowledge', weight: 0.6 }] },
    ],
  },
];
